package com.forum.model.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.replyid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    private Integer replyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.replytipid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    private Integer replytipid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.replyuserid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    private Integer replyuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.replytime
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date replytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.replyid
     *
     * @return the value of reply.replyid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public Integer getReplyid() {
        return replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.replyid
     *
     * @param replyid the value for reply.replyid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setReplyid(Integer replyid) {
        this.replyid = replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.replytipid
     *
     * @return the value of reply.replytipid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public Integer getReplytipid() {
        return replytipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.replytipid
     *
     * @param replytipid the value for reply.replytipid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setReplytipid(Integer replytipid) {
        this.replytipid = replytipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.replyuserid
     *
     * @return the value of reply.replyuserid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public Integer getReplyuserid() {
        return replyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.replyuserid
     *
     * @param replyuserid the value for reply.replyuserid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setReplyuserid(Integer replyuserid) {
        this.replyuserid = replyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.replytime
     *
     * @return the value of reply.replytime
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public Date getReplytime() {
        return replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.replytime
     *
     * @param replytime the value for reply.replytime
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }

	@Override
	public String toString() {
		return "Reply [replyid=" + replyid + ", replytipid=" + replytipid + ", replyuserid=" + replyuserid
				+ ", replytime=" + replytime + "]";
	}

	public Reply(Integer replyid, Integer replytipid, Integer replyuserid, Date replytime) {
		super();
		this.replyid = replyid;
		this.replytipid = replytipid;
		this.replyuserid = replyuserid;
		this.replytime = replytime;
	}

	public Reply() {
		super();
		// TODO Auto-generated constructor stub
	}
}