package com.forum.model.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Tip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.tipid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    private Integer tipid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.tipuserid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    private Integer tipuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.tipcount
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    private Integer tipcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.tiptopic
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    private String tiptopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.tipcontent
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    private String tipcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.tiptime
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd") 
    private Date tiptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.tipclick
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    private Integer tipclick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.tipimage
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    private String tipimage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.tipid
     *
     * @return the value of tip.tipid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public Integer getTipid() {
        return tipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.tipid
     *
     * @param tipid the value for tip.tipid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setTipid(Integer tipid) {
        this.tipid = tipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.tipuserid
     *
     * @return the value of tip.tipuserid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public Integer getTipuserid() {
        return tipuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.tipuserid
     *
     * @param tipuserid the value for tip.tipuserid
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setTipuserid(Integer tipuserid) {
        this.tipuserid = tipuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.tipcount
     *
     * @return the value of tip.tipcount
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public Integer getTipcount() {
        return tipcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.tipcount
     *
     * @param tipcount the value for tip.tipcount
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setTipcount(Integer tipcount) {
        this.tipcount = tipcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.tiptopic
     *
     * @return the value of tip.tiptopic
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public String getTiptopic() {
        return tiptopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.tiptopic
     *
     * @param tiptopic the value for tip.tiptopic
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setTiptopic(String tiptopic) {
        this.tiptopic = tiptopic == null ? null : tiptopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.tipcontent
     *
     * @return the value of tip.tipcontent
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public String getTipcontent() {
        return tipcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.tipcontent
     *
     * @param tipcontent the value for tip.tipcontent
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setTipcontent(String tipcontent) {
        this.tipcontent = tipcontent == null ? null : tipcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.tiptime
     *
     * @return the value of tip.tiptime
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public Date getTiptime() {
        return tiptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.tiptime
     *
     * @param tiptime the value for tip.tiptime
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setTiptime(Date tiptime) {
        this.tiptime = tiptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.tipclick
     *
     * @return the value of tip.tipclick
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public Integer getTipclick() {
        return tipclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.tipclick
     *
     * @param tipclick the value for tip.tipclick
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setTipclick(Integer tipclick) {
        this.tipclick = tipclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.tipimage
     *
     * @return the value of tip.tipimage
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public String getTipimage() {
        return tipimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.tipimage
     *
     * @param tipimage the value for tip.tipimage
     *
     * @mbg.generated Tue Sep 22 16:10:00 CST 2020
     */
    public void setTipimage(String tipimage) {
        this.tipimage = tipimage == null ? null : tipimage.trim();
    }

	@Override
	public String toString() {
		return "Tip [tipid=" + tipid + ", tipuserid=" + tipuserid + ", tipcount=" + tipcount + ", tiptopic=" + tiptopic
				+ ", tipcontent=" + tipcontent + ", tiptime=" + tiptime + ", tipclick=" + tipclick + ", tipimage="
				+ tipimage + "]";
	}

	public Tip(Integer tipid, Integer tipuserid, Integer tipcount, String tiptopic, String tipcontent, Date tiptime,
			Integer tipclick, String tipimage) {
		super();
		this.tipid = tipid;
		this.tipuserid = tipuserid;
		this.tipcount = tipcount;
		this.tiptopic = tiptopic;
		this.tipcontent = tipcontent;
		this.tiptime = tiptime;
		this.tipclick = tipclick;
		this.tipimage = tipimage;
	}

	public Tip() {
		super();
		// TODO Auto-generated constructor stub
	}
}